### ISSUE TITLE
Add support for "Go" and "Lite" apps on google play

### ISSUE THREAD

**Issue by ghost** [Magisk-Modules-Repo/xmlpak#4]

**Comment by TadiT7** [comment]
"Go" apps are forced to have a higher version number as per Google requirements, so they replace the standard ones. I'd add that, but that would have to be a config, can't ship it by default. What are "Lite" apps tho?

**Comment by ghost** [comment]
Probably the same as "go"
Some apps use the term lite but it looks like the same thing as "go"

Sent from ProtonMail mobile

-------- Original Message --------
